name: Update gist
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ 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 }}
          GIST_ID: ${{ https://gist.github.com/sky7214sky72/b4ff82bd37fe228e93926782fc968de2 }}
          TIMEZONE: Asia/Seoul
